runtime: python38

handlers:
- url: /pyodide/(.*\.wasm)$
  static_files: pyodide/\1
  upload: pyodide/.*\.wasm$
  mime_type: text/plain
- url: /static
  static_dir: static
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: favicon.ico


